# This file was automatically generated by Sbtix. Do not edit manually.
{
  "repos" = {
    "nix-public" = "";
  };
  "artifacts" = {
    "nix-public/org/scala-lang/modules/scala-xml_2.11/1.0.4/scala-xml_2.11-1.0.4.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/modules/scala-xml_2.11/1.0.4/scala-xml_2.11-1.0.4.jar";
      sha256 = "09aq9mwqkrq1w809aa02agygaaisfpda9pcfvifla7yrnydqx6zf";
    };
    "nix-public/org/scala-lang/modules/scala-xml_2.11/1.0.4/scala-xml_2.11-1.0.4.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/modules/scala-xml_2.11/1.0.4/scala-xml_2.11-1.0.4.pom";
      sha256 = "1ndyzsjrzw3j2qwffg88nm5kwnv6adj96azvxy2f62c3fh2bf9m4";
    };
    "nix-public/org/scala-lang/scala-compiler/2.11.8/scala-compiler-2.11.8.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-compiler/2.11.8/scala-compiler-2.11.8.pom";
      sha256 = "08m3s75j9b7ys4r9p0vsx2kxy6s63lchc1agycd40k5rh8kwb5pp";
    };
    "nix-public/org/scala-lang/scala-compiler/2.11.8/scala-compiler-2.11.8.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-compiler/2.11.8/scala-compiler-2.11.8.jar";
      sha256 = "09xckawr03bih4c98kq67y96sy13rcsfgz7phi8yv3qmxamd8w9j";
    };
    "nix-public/org/scala-lang/modules/scala-parser-combinators_2.11/1.0.4/scala-parser-combinators_2.11-1.0.4.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/modules/scala-parser-combinators_2.11/1.0.4/scala-parser-combinators_2.11-1.0.4.pom";
      sha256 = "19wm08gfwdyxlb8169wj1gpparh14d256j8yk74wfg2vx4zn50ic";
    };
    "nix-public/org/scala-lang/modules/scala-parser-combinators_2.11/1.0.4/scala-parser-combinators_2.11-1.0.4.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/modules/scala-parser-combinators_2.11/1.0.4/scala-parser-combinators_2.11-1.0.4.jar";
      sha256 = "1mk27z41nkd7yvqsj0qg6gqdharx0z0w43hqm6q4b8m9577azyhd";
    };
    "nix-public/org/scala-lang/scala-library/2.11.8/scala-library-2.11.8.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.11.8/scala-library-2.11.8.pom";
      sha256 = "1cj9504qyxhzsj778lkhsin71nbwz2gyvgcqjw0f6zvhvd7w4kwq";
    };
    "nix-public/org/scala-lang/scala-library/2.11.8/scala-library-2.11.8.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.11.8/scala-library-2.11.8.jar";
      sha256 = "1xp5lkn3fq5c624p4kw0kj8m17qnh3jg4d25jq8wh89jsr3hy7j0";
    };
    "nix-public/org/scala-lang/scala-reflect/2.11.8/scala-reflect-2.11.8.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.11.8/scala-reflect-2.11.8.pom";
      sha256 = "192ic5as6aph25fy6yh6f2ji157n0z2yd6qlygbmlczrya80icw2";
    };
    "nix-public/org/scala-lang/scala-reflect/2.11.8/scala-reflect-2.11.8.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.11.8/scala-reflect-2.11.8.jar";
      sha256 = "06a3idk3ywl7dy1fiy014j0aqqv8r1mnrq0ifj3dwd9ad9283q19";
    };
    "nix-public/org/reactivestreams/reactive-streams/1.0.0/reactive-streams-1.0.0.pom" = {
      url = "https://repo1.maven.org/maven2/org/reactivestreams/reactive-streams/1.0.0/reactive-streams-1.0.0.pom";
      sha256 = "065r7nlj7fwckzh0f1g0nnwkw50xbfhixdjzr4ij9wzbc31symd0";
    };
    "nix-public/org/reactivestreams/reactive-streams/1.0.0/reactive-streams-1.0.0.jar" = {
      url = "https://repo1.maven.org/maven2/org/reactivestreams/reactive-streams/1.0.0/reactive-streams-1.0.0.jar";
      sha256 = "1sx0kjvzfhqnibvmdq0spjmzrg8lbs7mmdjgqsv6xf8llq17g1pg";
    };
    "nix-public/com/typesafe/config/1.2.1/config-1.2.1.jar" = {
      url = "https://repo1.maven.org/maven2/com/typesafe/config/1.2.1/config-1.2.1.jar";
      sha256 = "1vmrx1pf5scm30rx0r0zhyk2898iw9f46kkrb8vw582iizbznq61";
    };
    "nix-public/com/typesafe/config/1.2.1/config-1.2.1.pom" = {
      url = "https://repo1.maven.org/maven2/com/typesafe/config/1.2.1/config-1.2.1.pom";
      sha256 = "0g5ahmv3qnw2md5jm3s9yhzkwhlv8k80n585ikzrz1j80kqiwdk2";
    };
    "nix-public/org/slf4j/slf4j-api/1.7.10/slf4j-api-1.7.10.pom" = {
      url = "https://repo1.maven.org/maven2/org/slf4j/slf4j-api/1.7.10/slf4j-api-1.7.10.pom";
      sha256 = "1c8ldjj2nvyd22xlrdainh1bs90srjrr3p9dg5s2qhk34a6mx75g";
    };
    "nix-public/org/slf4j/slf4j-api/1.7.10/slf4j-api-1.7.10.jar" = {
      url = "https://repo1.maven.org/maven2/org/slf4j/slf4j-api/1.7.10/slf4j-api-1.7.10.jar";
      sha256 = "1zib4f8lj0787di7v2j04ad5w4gaxw9v31xzi494s3bl0mqf4qrq";
    };
    "nix-public/org/scala-lang/scala-library/2.11.6/scala-library-2.11.6.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.11.6/scala-library-2.11.6.pom";
      sha256 = "1sr6rww4fmziqqbs0xw4pd71z9kha1hxkv9vn7v68ksxhlkimlm9";
    };
    "nix-public/org/scala-lang/scala-library/2.11.6/scala-library-2.11.6.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.11.6/scala-library-2.11.6.jar";
      sha256 = "0liqf7j5f6m77a4xpf8n8hbp5n4bpywy9xihz9wphn17gbvv1z5n";
    };
    "nix-public/com/typesafe/slick/slick_2.11/3.1.1/slick_2.11-3.1.1.jar" = {
      url = "https://repo1.maven.org/maven2/com/typesafe/slick/slick_2.11/3.1.1/slick_2.11-3.1.1.jar";
      sha256 = "0gxxqw0xf18in5yw366yhqahf4iaf53nfr32qfn0l2p0rz628rv3";
    };
    "nix-public/com/typesafe/slick/slick_2.11/3.1.1/slick_2.11-3.1.1.pom" = {
      url = "https://repo1.maven.org/maven2/com/typesafe/slick/slick_2.11/3.1.1/slick_2.11-3.1.1.pom";
      sha256 = "1npg3fl2kbga58k5yr2yfxv63xjj6rfi9nbmkfkb4zmbbl31iw76";
    };
  };
}
